name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (leave empty for patch bump)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
        
    - name: Release with JReleaser
      run: |
        set -e
        if [ -n "${{ github.event.inputs.version }}" ]; then
          echo "Setting version to ${{ github.event.inputs.version }}"
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.version }}
          mvn -B versions:commit
        else
          echo "Auto-incrementing patch version"
          mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}
          mvn -B versions:commit
        fi
        
        echo "Building and verifying..."
        mvn -B clean verify
        
        echo "Staging artifacts..."
        mkdir -p target/staging-deploy
        mvn -B deploy -DaltDeploymentRepository=local::file:./target/staging-deploy -DskipTests
        
        echo "Releasing with JReleaser..."
        mvn -B jreleaser:full-release
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}